apiVersion: apps/v1
kind: Deployment
metadata:
  name: ridecircle-app
  namespace: ridecircle
  labels:
    app: ridecircle-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ridecircle-app
  template:
    metadata:
      labels:
        app: ridecircle-app
    spec:
      containers:
      - name: ridecircle-app
        image: ridecircle/app:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: ridecircle-config
              key: NODE_ENV
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ridecircle-secrets
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: ridecircle-secrets
              key: REDIS_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: ridecircle-secrets
              key: JWT_SECRET
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: ridecircle-secrets
              key: JWT_REFRESH_SECRET
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: ridecircle-secrets
              key: ENCRYPTION_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ridecircle-app-service
  namespace: ridecircle
spec:
  selector:
    app: ridecircle-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
