apiVersion: v1
kind: Secret
metadata:
  name: ridecircle-secrets
  namespace: ridecircle
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded secrets
  DATABASE_URL: cG9zdGdyZXNxbDovL3JpZGVjaXJjbGU6cGFzc3dvcmRAcG9zdGdyZXM6NTQzMi9yaWRlY2lyY2xlX3Byb2Q=
  REDIS_URL: cmVkaXM6Ly9yZWRpczozNjM3OQ==
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWhlcmU=
  JWT_REFRESH_SECRET: eW91ci1yZWZyZXNoLXNlY3JldC1oZXJl
  ENCRYPTION_KEY: eW91ci1lbmNyeXB0aW9uLWtleS1oZXJl
